"""Added the rest of tables

Revision ID: 01f3743179f2
Revises: 4a8a0daf5d8b
Create Date: 2026-01-08 18:15:20.448070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01f3743179f2'
down_revision: Union[str, Sequence[str], None] = '4a8a0daf5d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farmer_invoice_payed')
    op.alter_column('carriage', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carriage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('carriage_village_id_fkey'), 'carriage', type_='foreignkey')
    op.drop_constraint(op.f('carriage_destination_id_fkey'), 'carriage', type_='foreignkey')
    op.drop_constraint(op.f('carriage_farmer_id_fkey'), 'carriage', type_='foreignkey')
    op.drop_constraint(op.f('carriage_origin_id_fkey'), 'carriage', type_='foreignkey')
    op.create_foreign_key(None, 'carriage', 'village', ['village_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'carriage', 'city', ['origin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'carriage', 'farmer', ['farmer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'carriage', 'city', ['destination_id'], ['id'], ondelete='CASCADE')
    op.alter_column('carriage_status', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('carriage_status', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('carriage_status_carriage_id_fkey'), 'carriage_status', type_='foreignkey')
    op.drop_constraint(op.f('carriage_status_driver_id_fkey'), 'carriage_status', type_='foreignkey')
    op.create_foreign_key(None, 'carriage_status', 'carriage', ['carriage_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'carriage_status', 'driver', ['driver_id'], ['id'], ondelete='CASCADE')
    op.alter_column('commitment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('commitment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_commitment_number'), table_name='commitment')
    op.drop_constraint(op.f('commitment_village_id_fkey'), 'commitment', type_='foreignkey')
    op.drop_constraint(op.f('commitment_crop_year_id_fkey'), 'commitment', type_='foreignkey')
    op.drop_constraint(op.f('commitment_user_id_fkey'), 'commitment', type_='foreignkey')
    op.drop_constraint(op.f('commitment_farmer_id_fkey'), 'commitment', type_='foreignkey')
    op.create_foreign_key(None, 'commitment', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'commitment', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'commitment', 'farmer', ['farmer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'commitment', 'village', ['village_id'], ['id'], ondelete='CASCADE')
    op.alter_column('crop_year', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_year', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_crop_year_name'), table_name='crop_year')
    op.create_index(op.f('ix_crop_year_crop_year_name'), 'crop_year', ['crop_year_name'], unique=False)
    op.alter_column('factory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_factory_name'), table_name='factory')
    op.create_index(op.f('ix_factory_factory_name'), 'factory', ['factory_name'], unique=False)
    op.alter_column('factory_commitment_tonnage', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_commitment_tonnage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('factory_commitment_tonnage_factory_id_fkey'), 'factory_commitment_tonnage', type_='foreignkey')
    op.drop_constraint(op.f('factory_commitment_tonnage_crop_year_id_fkey'), 'factory_commitment_tonnage', type_='foreignkey')
    op.create_foreign_key(None, 'factory_commitment_tonnage', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factory_commitment_tonnage', 'factory', ['factory_id'], ['id'], ondelete='CASCADE')
    op.alter_column('factory_payment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_payment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('factory_payment_factory_id_fkey'), 'factory_payment', type_='foreignkey')
    op.drop_constraint(op.f('factory_payment_crop_year_id_fkey'), 'factory_payment', type_='foreignkey')
    op.drop_constraint(op.f('factory_payment_user_id_fkey'), 'factory_payment', type_='foreignkey')
    op.create_foreign_key(None, 'factory_payment', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factory_payment', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factory_payment', 'factory', ['factory_id'], ['id'], ondelete='CASCADE')
    op.alter_column('factory_pesticide', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_pesticide', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('factory_pesticide_pesticide_id_fkey'), 'factory_pesticide', type_='foreignkey')
    op.drop_constraint(op.f('factory_pesticide_crop_year_id_fkey'), 'factory_pesticide', type_='foreignkey')
    op.drop_constraint(op.f('factory_pesticide_factory_id_fkey'), 'factory_pesticide', type_='foreignkey')
    op.create_foreign_key(None, 'factory_pesticide', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factory_pesticide', 'factory', ['factory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factory_pesticide', 'pesticide', ['pesticide_id'], ['id'], ondelete='CASCADE')
    op.alter_column('factory_seed', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_seed', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('factory_seed_seed_id_fkey'), 'factory_seed', type_='foreignkey')
    op.drop_constraint(op.f('factory_seed_factory_id_fkey'), 'factory_seed', type_='foreignkey')
    op.drop_constraint(op.f('factory_seed_crop_year_id_fkey'), 'factory_seed', type_='foreignkey')
    op.create_foreign_key(None, 'factory_seed', 'seed', ['seed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factory_seed', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factory_seed', 'factory', ['factory_id'], ['id'], ondelete='CASCADE')
    op.alter_column('factory_sugar', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_sugar', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('factory_sugar_factory_id_fkey'), 'factory_sugar', type_='foreignkey')
    op.drop_constraint(op.f('factory_sugar_crop_year_id_fkey'), 'factory_sugar', type_='foreignkey')
    op.create_foreign_key(None, 'factory_sugar', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factory_sugar', 'factory', ['factory_id'], ['id'], ondelete='CASCADE')
    op.alter_column('factory_waste', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_waste', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('factory_waste_crop_year_id_fkey'), 'factory_waste', type_='foreignkey')
    op.drop_constraint(op.f('factory_waste_factory_id_fkey'), 'factory_waste', type_='foreignkey')
    op.create_foreign_key(None, 'factory_waste', 'factory', ['factory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'factory_waste', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.add_column('farmer', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('farmer', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_national_id'), table_name='farmer')
    op.create_index(op.f('ix_farmer_national_id'), 'farmer', ['national_id'], unique=False)
    op.alter_column('farmers_guarantee', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_guarantee', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('farmers_guarantee_guarantor_farmer_id_fkey'), 'farmers_guarantee', type_='foreignkey')
    op.drop_constraint(op.f('farmers_guarantee_crop_year_id_fkey'), 'farmers_guarantee', type_='foreignkey')
    op.drop_constraint(op.f('farmers_guarantee_guaranteed_farmer_id_fkey'), 'farmers_guarantee', type_='foreignkey')
    op.create_foreign_key(None, 'farmers_guarantee', 'farmer', ['guarantor_farmer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_guarantee', 'farmer', ['guaranteed_farmer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_guarantee', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.alter_column('farmers_load', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_load', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('farmers_load_farmer_id_fkey'), 'farmers_load', type_='foreignkey')
    op.drop_constraint(op.f('farmers_load_factory_id_fkey'), 'farmers_load', type_='foreignkey')
    op.drop_constraint(op.f('farmers_load_crop_year_id_fkey'), 'farmers_load', type_='foreignkey')
    op.create_foreign_key(None, 'farmers_load', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_load', 'factory', ['factory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_load', 'farmer', ['farmer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('farmers_payment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_payment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('farmers_payment_payment_type_fkey'), 'farmers_payment', type_='foreignkey')
    op.drop_constraint(op.f('farmers_payment_farmer_id_fkey'), 'farmers_payment', type_='foreignkey')
    op.create_foreign_key(None, 'farmers_payment', 'farmer', ['farmer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('farmers_pesticide', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_pesticide', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('farmers_pesticide_pesticide_id_fkey'), 'farmers_pesticide', type_='foreignkey')
    op.drop_constraint(op.f('farmers_pesticide_crop_year_id_fkey'), 'farmers_pesticide', type_='foreignkey')
    op.drop_constraint(op.f('farmers_pesticide_factory_id_fkey'), 'farmers_pesticide', type_='foreignkey')
    op.drop_constraint(op.f('farmers_pesticide_commitment_id_fkey'), 'farmers_pesticide', type_='foreignkey')
    op.create_foreign_key(None, 'farmers_pesticide', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_pesticide', 'commitment', ['commitment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_pesticide', 'pesticide', ['pesticide_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_pesticide', 'factory', ['factory_id'], ['id'], ondelete='CASCADE')
    op.alter_column('farmers_seed', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_seed', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('farmers_seed_seed_id_fkey'), 'farmers_seed', type_='foreignkey')
    op.drop_constraint(op.f('farmers_seed_factory_id_fkey'), 'farmers_seed', type_='foreignkey')
    op.drop_constraint(op.f('farmers_seed_crop_year_id_fkey'), 'farmers_seed', type_='foreignkey')
    op.drop_constraint(op.f('farmers_seed_commitment_id_fkey'), 'farmers_seed', type_='foreignkey')
    op.create_foreign_key(None, 'farmers_seed', 'commitment', ['commitment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_seed', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_seed', 'seed', ['seed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_seed', 'factory', ['factory_id'], ['id'], ondelete='CASCADE')
    op.alter_column('farmers_sugar_delivery', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_sugar_delivery', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('farmers_sugar_delivery_farmer_id_fkey'), 'farmers_sugar_delivery', type_='foreignkey')
    op.drop_constraint(op.f('farmers_sugar_delivery_crop_year_id_fkey'), 'farmers_sugar_delivery', type_='foreignkey')
    op.create_foreign_key(None, 'farmers_sugar_delivery', 'farmer', ['farmer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_sugar_delivery', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.alter_column('farmers_waste_delivery', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_waste_delivery', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('farmers_waste_delivery_crop_year_id_fkey'), 'farmers_waste_delivery', type_='foreignkey')
    op.drop_constraint(op.f('farmers_waste_delivery_farmer_id_fkey'), 'farmers_waste_delivery', type_='foreignkey')
    op.create_foreign_key(None, 'farmers_waste_delivery', 'farmer', ['farmer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'farmers_waste_delivery', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.alter_column('measure_unit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('measure_unit', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_unit_name'), table_name='measure_unit')
    op.create_index(op.f('ix_measure_unit_unit_name'), 'measure_unit', ['unit_name'], unique=False)
    op.alter_column('payment_reason', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_reason', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_reason_name'), table_name='payment_reason')
    op.create_index(op.f('ix_payment_reason_reason_name'), 'payment_reason', ['reason_name'], unique=False)
    op.alter_column('pesticide', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pesticide', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pesticide_name'), table_name='pesticide')
    op.create_index(op.f('ix_pesticide_pesticide_name'), 'pesticide', ['pesticide_name'], unique=False)
    op.drop_constraint(op.f('pesticide_measure_unit_id_fkey'), 'pesticide', type_='foreignkey')
    op.create_foreign_key(None, 'pesticide', 'measure_unit', ['measure_unit_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_prodcut_name'), table_name='product')
    op.create_index(op.f('ix_product_product_name'), 'product', ['product_name'], unique=False)
    op.drop_constraint(op.f('product_crop_year_id_fkey'), 'product', type_='foreignkey')
    op.drop_constraint(op.f('product_measure_unit_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product', 'measure_unit', ['measure_unit_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product_price', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_price', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('product_price_crop_year_id_fkey'), 'product_price', type_='foreignkey')
    op.create_foreign_key(None, 'product_price', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.alter_column('purity_price', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('purity_price', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('purity_price_crop_year_id_fkey'), 'purity_price', type_='foreignkey')
    op.create_foreign_key(None, 'purity_price', 'crop_year', ['crop_year_id'], ['id'], ondelete='CASCADE')
    op.alter_column('seed', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('seed', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_seed_name'), table_name='seed')
    op.create_index(op.f('ix_seed_seed_name'), 'seed', ['seed_name'], unique=False)
    op.drop_constraint(op.f('seed_measure_unit_id_fkey'), 'seed', type_='foreignkey')
    op.create_foreign_key(None, 'seed', 'measure_unit', ['measure_unit_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seed', type_='foreignkey')
    op.create_foreign_key(op.f('seed_measure_unit_id_fkey'), 'seed', 'measure_unit', ['measure_unit_id'], ['id'], onupdate='CASCADE')
    op.drop_index(op.f('ix_seed_seed_name'), table_name='seed')
    op.create_index(op.f('ix_seed_name'), 'seed', ['seed_name'], unique=False)
    op.alter_column('seed', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('seed', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'purity_price', type_='foreignkey')
    op.create_foreign_key(op.f('purity_price_crop_year_id_fkey'), 'purity_price', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('purity_price', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('purity_price', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'product_price', type_='foreignkey')
    op.create_foreign_key(op.f('product_price_crop_year_id_fkey'), 'product_price', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('product_price', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_price', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_measure_unit_id_fkey'), 'product', 'measure_unit', ['measure_unit_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('product_crop_year_id_fkey'), 'product', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_product_product_name'), table_name='product')
    op.create_index(op.f('ix_prodcut_name'), 'product', ['product_name'], unique=False)
    op.alter_column('product', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'pesticide', type_='foreignkey')
    op.create_foreign_key(op.f('pesticide_measure_unit_id_fkey'), 'pesticide', 'measure_unit', ['measure_unit_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_pesticide_pesticide_name'), table_name='pesticide')
    op.create_index(op.f('ix_pesticide_name'), 'pesticide', ['pesticide_name'], unique=False)
    op.alter_column('pesticide', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pesticide', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_payment_reason_reason_name'), table_name='payment_reason')
    op.create_index(op.f('ix_reason_name'), 'payment_reason', ['reason_name'], unique=False)
    op.alter_column('payment_reason', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_reason', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_measure_unit_unit_name'), table_name='measure_unit')
    op.create_index(op.f('ix_unit_name'), 'measure_unit', ['unit_name'], unique=False)
    op.alter_column('measure_unit', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('measure_unit', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'farmers_waste_delivery', type_='foreignkey')
    op.drop_constraint(None, 'farmers_waste_delivery', type_='foreignkey')
    op.create_foreign_key(op.f('farmers_waste_delivery_farmer_id_fkey'), 'farmers_waste_delivery', 'farmer', ['farmer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_waste_delivery_crop_year_id_fkey'), 'farmers_waste_delivery', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('farmers_waste_delivery', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_waste_delivery', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'farmers_sugar_delivery', type_='foreignkey')
    op.drop_constraint(None, 'farmers_sugar_delivery', type_='foreignkey')
    op.create_foreign_key(op.f('farmers_sugar_delivery_crop_year_id_fkey'), 'farmers_sugar_delivery', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_sugar_delivery_farmer_id_fkey'), 'farmers_sugar_delivery', 'farmer', ['farmer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('farmers_sugar_delivery', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_sugar_delivery', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'farmers_seed', type_='foreignkey')
    op.drop_constraint(None, 'farmers_seed', type_='foreignkey')
    op.drop_constraint(None, 'farmers_seed', type_='foreignkey')
    op.drop_constraint(None, 'farmers_seed', type_='foreignkey')
    op.create_foreign_key(op.f('farmers_seed_commitment_id_fkey'), 'farmers_seed', 'commitment', ['commitment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_seed_crop_year_id_fkey'), 'farmers_seed', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_seed_factory_id_fkey'), 'farmers_seed', 'factory', ['factory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_seed_seed_id_fkey'), 'farmers_seed', 'seed', ['seed_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('farmers_seed', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_seed', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'farmers_pesticide', type_='foreignkey')
    op.drop_constraint(None, 'farmers_pesticide', type_='foreignkey')
    op.drop_constraint(None, 'farmers_pesticide', type_='foreignkey')
    op.drop_constraint(None, 'farmers_pesticide', type_='foreignkey')
    op.create_foreign_key(op.f('farmers_pesticide_commitment_id_fkey'), 'farmers_pesticide', 'commitment', ['commitment_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_pesticide_factory_id_fkey'), 'farmers_pesticide', 'factory', ['factory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_pesticide_crop_year_id_fkey'), 'farmers_pesticide', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_pesticide_pesticide_id_fkey'), 'farmers_pesticide', 'pesticide', ['pesticide_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('farmers_pesticide', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_pesticide', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'farmers_payment', type_='foreignkey')
    op.create_foreign_key(op.f('farmers_payment_farmer_id_fkey'), 'farmers_payment', 'farmer', ['farmer_id'], ['id'])
    op.create_foreign_key(op.f('farmers_payment_payment_type_fkey'), 'farmers_payment', 'payment_reason', ['payment_type'], ['id'])
    op.alter_column('farmers_payment', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_payment', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'farmers_load', type_='foreignkey')
    op.drop_constraint(None, 'farmers_load', type_='foreignkey')
    op.drop_constraint(None, 'farmers_load', type_='foreignkey')
    op.create_foreign_key(op.f('farmers_load_crop_year_id_fkey'), 'farmers_load', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_load_factory_id_fkey'), 'farmers_load', 'factory', ['factory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_load_farmer_id_fkey'), 'farmers_load', 'farmer', ['farmer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('farmers_load', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_load', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'farmers_guarantee', type_='foreignkey')
    op.drop_constraint(None, 'farmers_guarantee', type_='foreignkey')
    op.drop_constraint(None, 'farmers_guarantee', type_='foreignkey')
    op.create_foreign_key(op.f('farmers_guarantee_guaranteed_farmer_id_fkey'), 'farmers_guarantee', 'farmer', ['guaranteed_farmer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_guarantee_crop_year_id_fkey'), 'farmers_guarantee', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('farmers_guarantee_guarantor_farmer_id_fkey'), 'farmers_guarantee', 'farmer', ['guarantor_farmer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('farmers_guarantee', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('farmers_guarantee', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_farmer_national_id'), table_name='farmer')
    op.create_index(op.f('ix_national_id'), 'farmer', ['national_id'], unique=False)
    op.alter_column('farmer', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('farmer', 'updated_at')
    op.drop_constraint(None, 'factory_waste', type_='foreignkey')
    op.drop_constraint(None, 'factory_waste', type_='foreignkey')
    op.create_foreign_key(op.f('factory_waste_factory_id_fkey'), 'factory_waste', 'factory', ['factory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('factory_waste_crop_year_id_fkey'), 'factory_waste', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('factory_waste', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_waste', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'factory_sugar', type_='foreignkey')
    op.drop_constraint(None, 'factory_sugar', type_='foreignkey')
    op.create_foreign_key(op.f('factory_sugar_crop_year_id_fkey'), 'factory_sugar', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('factory_sugar_factory_id_fkey'), 'factory_sugar', 'factory', ['factory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('factory_sugar', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_sugar', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'factory_seed', type_='foreignkey')
    op.drop_constraint(None, 'factory_seed', type_='foreignkey')
    op.drop_constraint(None, 'factory_seed', type_='foreignkey')
    op.create_foreign_key(op.f('factory_seed_crop_year_id_fkey'), 'factory_seed', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('factory_seed_factory_id_fkey'), 'factory_seed', 'factory', ['factory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('factory_seed_seed_id_fkey'), 'factory_seed', 'seed', ['seed_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('factory_seed', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_seed', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'factory_pesticide', type_='foreignkey')
    op.drop_constraint(None, 'factory_pesticide', type_='foreignkey')
    op.drop_constraint(None, 'factory_pesticide', type_='foreignkey')
    op.create_foreign_key(op.f('factory_pesticide_factory_id_fkey'), 'factory_pesticide', 'factory', ['factory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('factory_pesticide_crop_year_id_fkey'), 'factory_pesticide', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('factory_pesticide_pesticide_id_fkey'), 'factory_pesticide', 'pesticide', ['pesticide_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('factory_pesticide', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_pesticide', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'factory_payment', type_='foreignkey')
    op.drop_constraint(None, 'factory_payment', type_='foreignkey')
    op.drop_constraint(None, 'factory_payment', type_='foreignkey')
    op.create_foreign_key(op.f('factory_payment_user_id_fkey'), 'factory_payment', 'user', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('factory_payment_crop_year_id_fkey'), 'factory_payment', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('factory_payment_factory_id_fkey'), 'factory_payment', 'factory', ['factory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('factory_payment', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_payment', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'factory_commitment_tonnage', type_='foreignkey')
    op.drop_constraint(None, 'factory_commitment_tonnage', type_='foreignkey')
    op.create_foreign_key(op.f('factory_commitment_tonnage_crop_year_id_fkey'), 'factory_commitment_tonnage', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('factory_commitment_tonnage_factory_id_fkey'), 'factory_commitment_tonnage', 'factory', ['factory_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('factory_commitment_tonnage', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory_commitment_tonnage', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_factory_factory_name'), table_name='factory')
    op.create_index(op.f('ix_factory_name'), 'factory', ['factory_name'], unique=False)
    op.alter_column('factory', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('factory', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_crop_year_crop_year_name'), table_name='crop_year')
    op.create_index(op.f('ix_crop_year_name'), 'crop_year', ['crop_year_name'], unique=False)
    op.alter_column('crop_year', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('crop_year', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'commitment', type_='foreignkey')
    op.drop_constraint(None, 'commitment', type_='foreignkey')
    op.drop_constraint(None, 'commitment', type_='foreignkey')
    op.drop_constraint(None, 'commitment', type_='foreignkey')
    op.create_foreign_key(op.f('commitment_farmer_id_fkey'), 'commitment', 'farmer', ['farmer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('commitment_user_id_fkey'), 'commitment', 'user', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('commitment_crop_year_id_fkey'), 'commitment', 'crop_year', ['crop_year_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('commitment_village_id_fkey'), 'commitment', 'village', ['village_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('ix_commitment_number'), 'commitment', ['commitment_number'], unique=False)
    op.alter_column('commitment', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('commitment', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'carriage_status', type_='foreignkey')
    op.drop_constraint(None, 'carriage_status', type_='foreignkey')
    op.create_foreign_key(op.f('carriage_status_driver_id_fkey'), 'carriage_status', 'driver', ['driver_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('carriage_status_carriage_id_fkey'), 'carriage_status', 'carriage', ['carriage_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('carriage_status', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carriage_status', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'carriage', type_='foreignkey')
    op.drop_constraint(None, 'carriage', type_='foreignkey')
    op.drop_constraint(None, 'carriage', type_='foreignkey')
    op.drop_constraint(None, 'carriage', type_='foreignkey')
    op.create_foreign_key(op.f('carriage_origin_id_fkey'), 'carriage', 'city', ['origin_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('carriage_farmer_id_fkey'), 'carriage', 'farmer', ['farmer_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('carriage_destination_id_fkey'), 'carriage', 'city', ['destination_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(op.f('carriage_village_id_fkey'), 'carriage', 'village', ['village_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('carriage', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('carriage', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('farmer_invoice_payed',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('payed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('farmer_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('crop_year_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], name=op.f('farmer_invoice_payed_crop_year_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], name=op.f('farmer_invoice_payed_farmer_id_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('farmer_invoice_payed_pkey'))
    )
    # ### end Alembic commands ###
