"""update all tables becasue of adding index

Revision ID: 8de2f6446344
Revises: f52222aeeda6
Create Date: 2026-01-03 20:55:11.123164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de2f6446344'
down_revision: Union[str, Sequence[str], None] = 'f52222aeeda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_car_name'), 'car', ['name'], unique=False)
    op.alter_column('city', 'province_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_city_city'), 'city', ['city'], unique=False)
    op.alter_column('driver', 'car_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_driver_national_code'), 'driver', ['national_code'], unique=False)
    op.create_index(op.f('ix_driver_phone_number'), 'driver', ['phone_number'], unique=False)
    op.alter_column('province', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_province_province'), 'province', ['province'], unique=False)
    op.create_index(op.f('ix_village_village'), 'village', ['village'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_village_village'), table_name='village')
    op.drop_index(op.f('ix_province_province'), table_name='province')
    op.alter_column('province', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_driver_phone_number'), table_name='driver')
    op.drop_index(op.f('ix_driver_national_code'), table_name='driver')
    op.alter_column('driver', 'car_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_city_city'), table_name='city')
    op.alter_column('city', 'province_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_car_name'), table_name='car')
    op.alter_column('car', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
