"""Fix the writing error in farmer table

Revision ID: efe8e5da8e71
Revises: 01f3743179f2
Create Date: 2026-01-12 21:02:18.306491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe8e5da8e71'
down_revision: Union[str, Sequence[str], None] = '01f3743179f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer', sa.Column('address', sa.String(), nullable=False))
    op.drop_column('farmer', 'addres')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer', sa.Column('addres', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('farmer', 'address')
    # ### end Alembic commands ###
