"""create initial tables

Revision ID: 089ccd0e2e05
Revises: b87e1deb9221
Create Date: 2026-02-04 18:37:11.919120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089ccd0e2e05'
down_revision: Union[str, Sequence[str], None] = 'b87e1deb9221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_name'), 'car', ['name'], unique=False)
    op.create_table('crop_year',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_year_crop_year_name'), 'crop_year', ['crop_year_name'], unique=False)
    op.create_table('factory',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('factory_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factory_factory_name'), 'factory', ['factory_name'], unique=False)
    op.create_table('farmer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('national_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('father_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('sheba_number_1', sa.String(), nullable=False),
    sa.Column('sheba_number_2', sa.String(), nullable=False),
    sa.Column('card_number', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_national_id'), 'farmer', ['national_id'], unique=False)
    op.create_table('measure_unit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measure_unit_unit_name'), 'measure_unit', ['unit_name'], unique=False)
    op.create_table('payment_reason',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('reason_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_reason_reason_name'), 'payment_reason', ['reason_name'], unique=False)
    op.create_table('province',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_province_province'), 'province', ['province'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('city',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_city'), 'city', ['city'], unique=False)
    op.create_table('driver',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('national_code', sa.String(length=10), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('capacity_ton', sa.Float(), nullable=True),
    sa.Column('car_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_national_code'), 'driver', ['national_code'], unique=False)
    op.create_index(op.f('ix_driver_phone_number'), 'driver', ['phone_number'], unique=False)
    op.create_table('factory_commitment_tonnage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('committed_tonnage_amount', sa.Float(), nullable=True),
    sa.Column('factory_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory_payment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('factory_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory_sugar',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('sugar_weight_received_factory', sa.Float(), nullable=True),
    sa.Column('sugar_price_received_factory', sa.Float(), nullable=True),
    sa.Column('factory_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory_waste',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('waste_weight_received_factory', sa.Float(), nullable=True),
    sa.Column('waste_price_received_factory', sa.Float(), nullable=True),
    sa.Column('factory_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmers_guarantee',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guarantee_price', sa.Float(), nullable=True),
    sa.Column('guarantor_farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('guaranteed_farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guaranteed_farmer_id'], ['farmer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guarantor_farmer_id'], ['farmer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmers_load',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('load_number', sa.String(), nullable=False),
    sa.Column('driver_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('dirt_weight', sa.Float(), nullable=True),
    sa.Column('pest_weight', sa.Float(), nullable=True),
    sa.Column('pure_weight', sa.Float(), nullable=True),
    sa.Column('sugar_beet_polarity', sa.Float(), nullable=True),
    sa.Column('price_per_kilo', sa.Float(), nullable=True),
    sa.Column('rent_help', sa.Float(), nullable=True),
    sa.Column('transportation_cost', sa.Float(), nullable=True),
    sa.Column('quota_sugar_price', sa.Float(), nullable=True),
    sa.Column('quota_pulp_price', sa.Float(), nullable=True),
    sa.Column('pure_payable', sa.Float(), nullable=True),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('factory_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmers_payment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('payment_type', sa.BigInteger(), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmers_sugar_delivery',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sugar_delivered', sa.Float(), nullable=False),
    sa.Column('sugar_deposit_amount', sa.Float(), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmers_waste_delivery',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('waste_delivered', sa.Float(), nullable=False),
    sa.Column('waste_deposit_amount', sa.Float(), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pesticide',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pesticide_name', sa.String(), nullable=False),
    sa.Column('measure_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['measure_unit_id'], ['measure_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesticide_pesticide_name'), 'pesticide', ['pesticide_name'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('measure_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['measure_unit_id'], ['measure_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_product_name'), 'product', ['product_name'], unique=False)
    op.create_table('product_price',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sugar_amount_per_ton_kg', sa.Float(), nullable=False),
    sa.Column('sugar_price_per_kg', sa.Float(), nullable=False),
    sa.Column('pulp_amount_per_ton_kg', sa.Float(), nullable=False),
    sa.Column('pulp_price_per_kg', sa.Float(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purity_price',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('base_purity', sa.Float(), nullable=False),
    sa.Column('base_purity_price', sa.Float(), nullable=False),
    sa.Column('price_difference', sa.Float(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('seed_name', sa.String(), nullable=False),
    sa.Column('measure_unit_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['measure_unit_id'], ['measure_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_seed_name'), 'seed', ['seed_name'], unique=False)
    op.create_table('factory_pesticide',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('farmer_price', sa.Float(), nullable=True),
    sa.Column('factory_price', sa.Float(), nullable=True),
    sa.Column('factory_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('pesticide_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pesticide_id'], ['pesticide.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factory_seed',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('farmer_price', sa.Float(), nullable=True),
    sa.Column('factory_price', sa.Float(), nullable=True),
    sa.Column('factory_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('seed_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seed_id'], ['seed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('village',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('village', sa.String(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_village_village'), 'village', ['village'], unique=False)
    op.create_table('carriage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('loading_date', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('carriage_fee_per_ton', sa.Float(), nullable=False),
    sa.Column('origin_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_id', sa.BigInteger(), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('village_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['city.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_id'], ['city.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commitment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('commitment_number', sa.String(length=50), nullable=False),
    sa.Column('amount_of_land', sa.Float(), nullable=False),
    sa.Column('withdrawal_amount', sa.Float(), nullable=False),
    sa.Column('date_set', sa.DateTime(), nullable=True),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('farmer_id', sa.BigInteger(), nullable=False),
    sa.Column('village_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carriage_status',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('carried', sa.Boolean(), nullable=True),
    sa.Column('carriage_id', sa.BigInteger(), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carriage_id'], ['carriage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmers_pesticide',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pesticide_amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_for_all_farmers_checkbox', sa.Boolean(), nullable=True),
    sa.Column('commitment_id', sa.BigInteger(), nullable=False),
    sa.Column('pesticide_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('factory_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pesticide_id'], ['pesticide.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmers_seed',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('seed_amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_for_all_farmers_checkbox', sa.Boolean(), nullable=True),
    sa.Column('commitment_id', sa.BigInteger(), nullable=False),
    sa.Column('seed_id', sa.BigInteger(), nullable=False),
    sa.Column('crop_year_id', sa.BigInteger(), nullable=False),
    sa.Column('factory_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_year_id'], ['crop_year.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seed_id'], ['seed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farmers_seed')
    op.drop_table('farmers_pesticide')
    op.drop_table('carriage_status')
    op.drop_table('commitment')
    op.drop_table('carriage')
    op.drop_index(op.f('ix_village_village'), table_name='village')
    op.drop_table('village')
    op.drop_table('factory_seed')
    op.drop_table('factory_pesticide')
    op.drop_index(op.f('ix_seed_seed_name'), table_name='seed')
    op.drop_table('seed')
    op.drop_table('purity_price')
    op.drop_table('product_price')
    op.drop_index(op.f('ix_product_product_name'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_pesticide_pesticide_name'), table_name='pesticide')
    op.drop_table('pesticide')
    op.drop_table('farmers_waste_delivery')
    op.drop_table('farmers_sugar_delivery')
    op.drop_table('farmers_payment')
    op.drop_table('farmers_load')
    op.drop_table('farmers_guarantee')
    op.drop_table('factory_waste')
    op.drop_table('factory_sugar')
    op.drop_table('factory_payment')
    op.drop_table('factory_commitment_tonnage')
    op.drop_index(op.f('ix_driver_phone_number'), table_name='driver')
    op.drop_index(op.f('ix_driver_national_code'), table_name='driver')
    op.drop_table('driver')
    op.drop_index(op.f('ix_city_city'), table_name='city')
    op.drop_table('city')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_province_province'), table_name='province')
    op.drop_table('province')
    op.drop_index(op.f('ix_payment_reason_reason_name'), table_name='payment_reason')
    op.drop_table('payment_reason')
    op.drop_index(op.f('ix_measure_unit_unit_name'), table_name='measure_unit')
    op.drop_table('measure_unit')
    op.drop_index(op.f('ix_farmer_national_id'), table_name='farmer')
    op.drop_table('farmer')
    op.drop_index(op.f('ix_factory_factory_name'), table_name='factory')
    op.drop_table('factory')
    op.drop_index(op.f('ix_crop_year_crop_year_name'), table_name='crop_year')
    op.drop_table('crop_year')
    op.drop_index(op.f('ix_car_name'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
