"""Fix some misspled words

Revision ID: b87e1deb9221
Revises: efe8e5da8e71
Create Date: 2026-01-12 21:05:54.799220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87e1deb9221'
down_revision: Union[str, Sequence[str], None] = 'efe8e5da8e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factory_commitment_tonnage', sa.Column('committed_tonnage_amount', sa.Float(), nullable=True))
    op.drop_column('factory_commitment_tonnage', 'commited_tonnage_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factory_commitment_tonnage', sa.Column('commited_tonnage_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('factory_commitment_tonnage', 'committed_tonnage_amount')
    # ### end Alembic commands ###
